server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zsl317309
